branches: # safelist
  only:
  - master
  - /^greenkeeper\/.*$/

sudo: required # required for docker in travis

language: node_js
node_js: "10.16.3"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.local

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@2

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn test

after_script:
  - greenkeeper-lockfile-upload
